# Generated by Django 4.1.5 on 2023-01-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-created'], 'verbose_name': 'servicio'},
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='services',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='services', verbose_name='Imangen'),
        ),
        migrations.AlterField(
            model_name='services',
            name='subtitle',
            field=models.CharField(max_length=500, verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='services',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion'),
        ),
    ]
